---
apiVersion: v1
kind: Service
metadata:
  name: antelope
  namespace: cloudplex-system
spec:
  ports:
  - name: http
    port: 9081
    protocol: TCP
    targetPort: 9081
  selector:
    app: antelope
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    keel.sh/match-tag: 'true'
    keel.sh/policy: all
  name: antelope
  namespace: cloudplex-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: antelope
  template:
    metadata:
      labels:
        app: antelope
    spec:
      containers:
      - env:
        - name: mongo_host
          value: "cloudplex-mongodb.cloudplex-system.svc.cluster.local:27017,mongodb-secondary-0.cloudplex-mongodb-headless:27017,mongodb-arbiter-0.cloudplex-mongodb-headless:27017"
        - name: mongo_pass
          valueFrom:
            secretKeyRef:
              name: antelope-database-credentials
              key: password
        - name: mongo_user
          valueFrom:
            secretKeyRef:
              name: antelope-database-credentials
              key: username
        - name: redis_url
          value: redis:6379
        - name: logger_url
          value: elephant:3500
        - name: network_url
          value: weasel:9080
        - name: mongo_auth
          value: 'true'
        - name: mongo_db
          valueFrom:
            secretKeyRef:
              name: antelope-database-credentials
              key: database
        - name: mongo_aws_template_collection
          value: aws_template
        - name: mongo_aws_cluster_collection
          value: aws_cluster
        - name: mongo_azure_template_collection
          value: azure_template
        - name: mongo_azure_cluster_collection
          value: azure_cluster
        - name: mongo_ssh_keys_collection
          value: ssh_key
        - name: vault_url
          value: robin:8092
        - name: racoon_url
          value: raccoon:5000
        - name: mongo_gcp_cluster_collection
          value: gcp_cluster
        - name: mongo_gcp_template_collection
          value: gcp_template
        - name: caCertificate
          value: /cloudplex/certificates/cloudplex.crt
        - name: clientCert
            value: /certificates/mongodb.crt
        - name: clientPem
            value: /certificates/mongodb.pem
        image: gcr.io/cloudplex-nextgen/antelope:186
        imagePullPolicy: IfNotPresent
        name: antelope
        ports:
        - containerPort: 9081
          protocol: TCP
      dnsPolicy: ClusterFirst
      volumeMounts:
        - mountPath: /certificates/
            name: mongodb-goose-certificates
            readOnly: true
        - mountPath: /cloudplex/certificates/
            name: cloudplex-certificates
            readOnly: true
      volumes:
      - name: antelope-database-credentials
        secret:
          secretName: antelope-database-credentials
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
---